export const LIST_CHARACTERS = 'home/LIST_CHARACTERS'
export const COUNTER_CHARACTERS = 'home/COUNTER_CHARACTERS'
export const LOADING = 'home/LOADING'
export const SET_OFFSET = 'home/SET_OFFSET'
export const SET_ARR_FOOTERNAV = 'home/SET_ARR_FOOTERNAV'